spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: microuser
    password: micropass
    url: jdbc:postgresql://localhost:5432/microservicedb

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG
      hibernate:
        SQL: DEBUG
        tool:
          hbm2ddl: DEBUG

server:
  port: 8093

app:
  updatedb: true